# Generated by Django 2.2.4 on 2019-08-17 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
